import type { AssetResolver } from '@pneuma-craft/video';

/**
 * A simple AssetResolver for the demo.
 * Maps asset IDs (generated by the store) to their public URLs.
 * The mapping is populated dynamically after assets are registered.
 */
class DemoAssetResolver implements AssetResolver {
  private readonly urlMap = new Map<string, string>();

  register(assetId: string, url: string): void {
    this.urlMap.set(assetId, url);
  }

  resolveUrl(assetId: string): string {
    return this.urlMap.get(assetId) ?? '';
  }

  async fetchBlob(assetId: string): Promise<Blob> {
    const url = this.resolveUrl(assetId);
    if (!url) throw new Error(`Unknown asset: ${assetId}`);
    const res = await fetch(url);
    return res.blob();
  }
}

export const assetResolver = new DemoAssetResolver();
